version: "3"

services:
  flask:
    build:
      context: .
      dockerfile: flask_app/Dockerfile
    volumes:
      - ".:/app"
    ports:
      - 5000:5000

  react:
    build:
      context: .
      dockerfile: react_app/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true